### ISSUE TITLE
branchen event

### ISSUE THREAD

**Issue by aaaeide** [Gabeorama/Gabeorama-Web#3]
hva er den

ps
er det en måte å diskutere prosjektet uten å poste en issue

**Comment by Balonbal** [comment]
Det er et prosjekt jeg startet med for flere hundre år siden, hvor målet var å lage en side hvor det var mulig å organisere events. Det er egentlig blitt til mer et lite prosjekt for å lære PHP og MYSQL.

Issues er basically githubs tråder, men det hjelper å tagge med `question`-labelen (FTFY).

**Comment by aaaeide** [comment]
aha

siggen kan greit med php forresten
